---
scenario:
  name: default

dependency:
  name: galaxy

driver:
  name: podman
platforms:
  - name: container-el7
    image: centos:7
    pre_build_image: true
  - name: container-el8
    image: centos:8
    pre_build_image: true
  - name: container-fedora31
    image: fedora:31
    pre_build_image: true
  - name: container-fedora32
    image: fedora:32
    pre_build_image: true

# driver:
#   name: vagrant
#   provider:
#     name: libvirt
# platforms:
#   - name: instance
#     box: generic/ubuntu1804

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        interpreter_python: "auto_silent"

verifier:
  name: testinfra
  lint:
    name: flake8
