# Static base inventory for this Molecule scenario
#
# This scenario supports both Ansible collections and standalone roles.
# The artifact type is auto-detected based on file existence:
#   - galaxy.yml present -> collection
#   - meta/main.yml present -> role
#
# To override auto-detection, uncomment and set artifact_type below.

---

all:
  hosts: {}
  children:
    # In this scenario, Molecule runs entirely on the local machine to build and
    # test an Execution Environment (EE) image.
    molecule:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          podman_executable: "{{ lookup('env', 'MOLECULE_PODMAN_EXECUTABLE') | ansible.builtin.default('podman', true) }}"
          # Uncomment to override artifact type auto-detection:
          # artifact_type: "collection"  # or "role"
    molecule_linux:
      hosts: {}
    molecule_windows:
      hosts: {}
